### ISSUE TITLE
Wrong mapping of tac indices

### ISSUE THREAD

**Issue by roterEmil** [stg-tud/opal-backup#44]
openjdk 8 version 265
class: sun.nio.cs.IBM874
The clinit method is not correct map from bytecode to tac:

pc2Index-array:
19->7
 20->0
 21->8
 22->0
 23->0
 24->8
 25->0

bytecode:
16     95     SIPUSH(256)
19     95     NEWARRAY(char[])
21     95     PUTSTATIC(sun.nio.cs.IBM874.c2bIndex : char[])
24     98     GETSTATIC(sun.nio.cs.IBM874.b2c : char[])
27     98     ASTORE_0
28     99     ACONST_NULL
29     99     ASTORE_1
30     101 LDC("€�������������������������� �����่กขฃคฅฆงจฉชซฌญฎฏฐฑฒณดตถทธนบปผฝพฟภมยรฤลฦวศษสหฬอฮฯะัาำิีึืฺุู้๊๋์฿เแโใไๅๆ็่้๊๋์ํ๎๏๐๑๒๓๔๕๖๗๘๙๚๛¢¬¦  \b\t\n\r !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~")
32     101    INVOKEVIRTUAL(java.lang.String{ char[] toCharArray() })
35     101    ASTORE_0
36     102    ALOAD_0

tac:
6: lv6 = 256
    7: lv7 = new char[{lv6}]
    8: sun.nio.cs.IBM874.c2bIndex = {lv7}
    9: lv9 = null
   10: lva = "€�������������������������������่กขฃคฅฆงจฉชซฌญฎฏฐฑฒณดตถทธนบปผฝพฟภมยรฤลฦวศษสหฬอฮฯะัาำิีึืฺุู้๊๋์฿เแโใไๅๆ็่้๊๋์ํ๎๏๐๑๒๓๔๕๖๗๘๙๚๛¢¬¦  \b\t\n       \r !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"
   11: lvb = {lva}/*java.lang.String*/.toCharArray()

**Comment by errt** [comment]
The problem originates in org.opalj.tac.TACAI where addNOPAndKillOperandBasedUsages doesn't add a statement because it is side-effect free and unused, but still adds the current index, pointing to some unrelated instruction, into the pcToIndex mapping. I suppose changing this method to instead add -1 into pcToIndex should fix the problem. However, I'm not currently sure that this won't break anything else

**Comment by errt** [comment]
Here is a minimal class that reproduces this behavior:
```
public class Test {
    private static final char[] t = new char[256];

    static {
        char[] l = t;
        l = "".toCharArray();
    }
}
```
